# Build configuration for build_runner

targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:
          - lib/**/*.dart
          - test/**/*.dart
        options:
          # Generate copyWith methods
          copy_with: true
          # Generate toJson/fromJson
          to_json: true
          from_json: true
          # Generate equality methods
          equal: true
          # Map config
          map: true

      json_serializable:
        enabled: true
        generate_for:
          - lib/**/*.dart
          - test/**/*.dart
        options:
          # Generate code for all fields including private ones
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

      riverpod_generator:
        enabled: true
        generate_for:
          - lib/**/*.dart
        options:
          # Riverpod generation options
