// Mocks generated by Mockito 5.4.6 from annotations
// in rapid_photo_mobile/test/features/gallery/providers/gallery_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:rapid_photo_mobile/features/gallery/models/paged_photos_response.dart'
    as _i2;
import 'package:rapid_photo_mobile/features/gallery/models/photo_response.dart'
    as _i3;
import 'package:rapid_photo_mobile/features/gallery/services/gallery_service.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePagedPhotosResponse_0 extends _i1.SmartFake
    implements _i2.PagedPhotosResponse {
  _FakePagedPhotosResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePhotoResponse_1 extends _i1.SmartFake implements _i3.PhotoResponse {
  _FakePhotoResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GalleryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGalleryService extends _i1.Mock implements _i4.GalleryService {
  MockGalleryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PagedPhotosResponse> getPhotos({
    int? page = 0,
    int? size = 20,
    String? sortBy,
    String? sortDirection,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPhotos,
          [],
          {
            #page: page,
            #size: size,
            #sortBy: sortBy,
            #sortDirection: sortDirection,
          },
        ),
        returnValue: _i5.Future<_i2.PagedPhotosResponse>.value(
            _FakePagedPhotosResponse_0(
          this,
          Invocation.method(
            #getPhotos,
            [],
            {
              #page: page,
              #size: size,
              #sortBy: sortBy,
              #sortDirection: sortDirection,
            },
          ),
        )),
      ) as _i5.Future<_i2.PagedPhotosResponse>);

  @override
  _i5.Future<_i2.PagedPhotosResponse> searchPhotosByTag({
    required List<String>? tags,
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPhotosByTag,
          [],
          {
            #tags: tags,
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i5.Future<_i2.PagedPhotosResponse>.value(
            _FakePagedPhotosResponse_0(
          this,
          Invocation.method(
            #searchPhotosByTag,
            [],
            {
              #tags: tags,
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i5.Future<_i2.PagedPhotosResponse>);

  @override
  _i5.Future<_i3.PhotoResponse> getPhoto(String? photoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPhoto,
          [photoId],
        ),
        returnValue: _i5.Future<_i3.PhotoResponse>.value(_FakePhotoResponse_1(
          this,
          Invocation.method(
            #getPhoto,
            [photoId],
          ),
        )),
      ) as _i5.Future<_i3.PhotoResponse>);

  @override
  _i5.Future<void> deletePhoto(String? photoId) => (super.noSuchMethod(
        Invocation.method(
          #deletePhoto,
          [photoId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getDownloadUrl(
    String? photoId, {
    String? versionType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDownloadUrl,
          [photoId],
          {#versionType: versionType},
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getDownloadUrl,
            [photoId],
            {#versionType: versionType},
          ),
        )),
      ) as _i5.Future<String>);
}
