/**
 * Amplify Gen2 configuration
 * This file configures AWS Amplify for authentication and storage.
 *
 * After running `npm run amplify:sandbox`, the amplify_outputs.json file
 * will be automatically generated with your backend configuration.
 */

import { Amplify } from 'aws-amplify';

// Try to import amplify_outputs.json if it exists (generated by Amplify Gen2)
// If it doesn't exist, fall back to environment variables
let amplifyConfig;

try {
  // @ts-ignore - This file is generated by Amplify CLI
  const outputs = await import('../../amplify_outputs.json');
  amplifyConfig = outputs.default;
} catch {
  // Fallback to manual configuration from environment variables
  amplifyConfig = {
    Auth: {
      Cognito: {
        userPoolId: import.meta.env.VITE_COGNITO_USER_POOL_ID || '',
        userPoolClientId: import.meta.env.VITE_COGNITO_CLIENT_ID || '',
        identityPoolId: import.meta.env.VITE_COGNITO_IDENTITY_POOL_ID || '',
        loginWith: {
          email: true,
        },
        signUpVerificationMethod: 'code' as const,
        userAttributes: {
          email: {
            required: true,
          },
        },
        allowGuestAccess: false,
        passwordFormat: {
          minLength: 8,
          requireLowercase: true,
          requireUppercase: true,
          requireNumbers: true,
          requireSpecialCharacters: false,
        },
      },
    },
    Storage: {
      S3: {
        bucket: import.meta.env.VITE_S3_BUCKET_NAME || '',
        region: import.meta.env.VITE_AWS_REGION || 'us-east-1',
      },
    },
  };
}

export const configureAmplify = () => {
  Amplify.configure(amplifyConfig);
};

export default amplifyConfig;
